export const PCG_COMPLET = {
  '10': 'Capital',
  '11': 'Réserves et primes liées au capital',
  '12': 'Résultats reportés',
  '13': 'Résultat de l\'exercice',
  '14': 'Autres capitaux propres',
  '15': 'Provisions pour risques & charges',
  '16': 'Emprunts & dettes assimilées',
  '17': 'Comptes de liaison des établissements & succursales',
  '18': 'Autres passifs non courants',
  '21': 'Immobilisations incorporelles',
  '22': 'Immobilisations corporelles',
  '23': 'Immobilisations en cours',
  '24': 'Immobilisations à statut juridique particulier',
  '25': 'Participations & créances liées à des participations',
  '26': 'Autres immobilisations financières',
  '27': 'Autres actifs non courants',
  '28': 'Amortissements des immobilisations',
  '29': 'Provisions pour dépréciation des actifs immobilisés',
  '31': 'Matières premières & fournitures liées',
  '32': 'Autres approvisionnements',
  '33': 'En-cours de production de biens',
  '34': 'En-cours de production de services',
  '35': 'Stocks de produits',
  '37': 'Stocks de marchandises',
  '39': 'Provisions pour dépréciation des stocks',
  '40': 'Fournisseurs et comptes rattachés',
  '41': 'Clients et comptes rattachés',
  '42': 'Personnel & comptes rattachés',
  '43': 'Etat & collectivités publiques',
  '44': 'Sociétés du groupe & associés',
  '45': 'Débiteurs divers & créditeurs divers',
  '46': 'Comptes transitoires ou d\'attente',
  '47': 'Comptes de régularisation',
  '48': 'Provisions courantes pour risques et charges',
  '49': 'Provisions pour dépréciation des comptes de tiers',
  '50': 'Emprunts et autres dettes financières courants',
  '51': 'Prêts et autres créances financières courants',
  '52': 'Placements courants',
  '53': 'Banques, établissements financiers et assimilés',
  '54': 'Caisse',
  '55': 'Régies d\'avances & accréditifs',
  '58': 'Virements internes',
  '59': 'Provisions pour dépréciation des comptes financiers',
  '60': 'Achats (sauf 603)',
  '61': 'Services extérieurs',
  '62': 'Autres services extérieurs',
  '63': 'Charges diverses ordinaires',
  '64': 'Charges de personnel',
  '65': 'Charges financières',
  '66': 'Impôts, taxes et versements assimilés',
  '67': 'Pertes extraordinaires',
  '68': 'Dotations aux amortissements et aux provisions',
  '69': 'Impôts sur les bénéfices',
  '70': 'Ventes de produits fabriqués, prestations de services, marchandises',
  '71': 'Production stockée (ou déstockage)',
  '72': 'Production immobilisée',
  '73': 'Produits divers ordinaires',
  '74': 'Subventions d\'exploitation et d\'équilibre',
  '75': 'Produits financiers',
  '77': 'Gains extraordinaires',
  '78': 'Reprises sur amortissements et provisions',
  '79': 'Transferts de charges',
  '101': 'Capital social',
  '105': 'Fonds de dotation',
  '108': 'Compte de l\'exploitant',
  '109': 'Actionnaires, capital souscrit - non appelé',
  '111': 'Réserve légale',
  '112': 'Réserves statutaires',
  '117': 'Primes liées au capital',
  '118': 'Autres réserves',
  '119': 'Avoirs des actionnaires',
  '121': 'Résultats reportés',
  '128': 'Modifications comptables affectant les résultats reportés',
  '131': 'Résultat bénéficiaire',
  '135': 'Résultat déficitaire',
  '141': 'Titres soumis à des réglementations particulières',
  '142': 'Réserves réglementées & réserves soumises à un régime fiscal particulier',
  '143': 'Amortissements dérogatoires',
  '144': 'Réserve spéciale de réévaluation',
  '145': 'Subventions d\'investissement',
  '147': 'Compte du concédant',
  '151': 'Provisions pour risques',
  '152': 'Provisions pour charges à répartir sur plusieurs exercices',
  '153': 'Provisions pour retraites et obligations similaires',
  '154': 'Provisions d\'origine réglementaire',
  '155': 'Provisions pour impôts',
  '156': 'Provisions pour renouvellement des immobilisations',
  '157': 'Provisions pour amortissement',
  '158': 'Autres provisions pour charges',
  '161': 'Emprunts obligataires (assorties de sûretés)',
  '162': 'Emprunts auprès des établissements financiers (assorties de sûretés)',
  '163': 'Emprunts auprès d\'autres établissements financiers (assorties de sûretés)',
  '164': 'Emprunts et dettes assorties de conditions particulières',
  '165': 'Emprunts non assorties de sûretés',
  '166': 'Dettes rattachées à des participations',
  '167': 'Dépôts & cautionnements reçus',
  '168': 'Autres emprunts et dettes',
  '171': 'Comptes des liaison des établissements',
  '176': 'Biens & prestations de services échangés entre établissements (charges)',
  '177': 'Biens & prestations de services échangés entre établissements (produits)',
  '185': 'Écarts de conversion',
  '188': 'Autres',
  '211': 'Investissements de recherche & de développement',
  '212': 'Concessions de marques, brevets, licences, marques, procédés & valeurs similaires',
  '213': 'Logiciels',
  '214': 'Fonds commercial',
  '216': 'Droit au bail',
  '218': 'Autres immobilisations incorporelles',
  '221': 'Terrains',
  '222': 'Constructions',
  '223': 'Installations techniques, matériel et outillage industriels',
  '224': 'Matériel de transport',
  '228': 'Autres immobilisations corporelles',
  '231': 'Immobilisations incorporelles en cours',
  '232': 'Immobilisations corporelles en cours',
  '237': 'Avances & acomptes versés sur immobilisations incorporelles',
  '238': 'Avances & acomptes versés sur commandes d\'immobilisations corporelles',
  '251': 'Titres de participation',
  '256': 'Autres formes de participation',
  '257': 'Créances rattachées à des participations',
  '258': 'Créances rattachées à des sociétés en participation',
  '259': 'Versements restant à effectuer sur titres de participation non libérés',
  '261': 'Titres immobilisés (droit de propriété)',
  '262': 'Titres immobilisés (droit de créance)',
  '264': 'Prêts',
  '265': 'Dépôts et cautionnements versés',
  '266': 'Autres créances immobilisées',
  '269': 'Versements restant à effectuer sur titres immobilisés non libérés',
  '271': 'Frais préliminaires',
  '272': 'Charges à répartir',
  '273': 'Frais d\'émission et primes de remboursement des emprunts',
  '275': 'Écarts de conversion',
  '278': 'Autres',
  '281': 'Amortissements des immobilisations incorporelles',
  '282': 'Amortissements des immobilisations corporelles',
  '284': 'Amortissements des immobilisations à statut juridique particulier',
  '291': 'Provisions pour dépréciation des immobilisations incorporelles',
  '292': 'Provisions pour dépréciation des immobilisations corporelles',
  '293': 'Provisions pour dépréciation des immobilisations en cours',
  '294': 'Provisions pour dépréciation des immobilisations à statut juridique particulier',
  '295': 'Provisions pour dépréciation des participations et des créances liées à des participations',
  '296': 'Provisions pour dépréciation des autres immobilisations financières',
  '311': 'Matières premières',
  '313': 'Fournitures',
  '317': 'Autres',
  '321': 'Matières consommables',
  '322': 'Fournitures consommables',
  '326': 'Emballages',
  '327': 'Autres',
  '331': 'Produits en cours',
  '335': 'Travaux en cours',
  '341': 'Études en cours',
  '345': 'Prestations de services en cours',
  '351': 'Produits intermédiaires',
  '355': 'Produits finis',
  '357': 'Produits résiduels',
  '401': 'Fournisseurs d\'exploitation',
  '403': 'Fournisseurs d\'exploitation - effets à payer',
  '404': 'Fournisseurs d\'immobilisations',
  '405': 'Fournisseurs d\'immobilisations - effets à payer',
  '408': 'Fournisseurs - factures non parvenues',
  '409': 'Fournisseurs débiteurs',
  '411': 'Clients',
  '413': 'Clients - effets à recevoir',
  '416': 'Clients douteux ou litigieux',
  '417': 'Créances sur travaux non encore facturables',
  '418': 'Clients - produits non encore facturés (produits à recevoir)',
  '419': 'Clients créditeurs',
  '421': 'Personnel - avances et acomptes',
  '422': 'Comités d\'entreprises et autres organes représentatifs du personnel',
  '423': 'Personnel, œuvres sociales',
  '425': 'Personnel - rémunérations dues',
  '426': 'Personnel - dépôts',
  '427': 'Personnel - oppositions',
  '428': 'Personnel - charges à payer & produits à recevoir',
  '431': 'Etat - subventions à recevoir',
  '432': 'Etat, impôts et taxes retenus à la source',
  '433': 'Opérations particulières avec l\'Etat, les collectivités publiques, les organismes internationaux',
  '434': 'Etat - impôts sur les bénéfices',
  '435': 'Obligations cautionnées',
  '436': 'Etat - taxes sur le chiffre d\'affaires',
  '437': 'Autres impôts, taxes et versements assimilés',
  '438': 'Etat - charges à payer et produits à recevoir',
  '441': 'Groupe',
  '442': 'Associés - comptes courants',
  '446': 'Associés - opérations sur le capital',
  '447': 'Associés - dividendes à payer',
  '448': 'Associés - opérations faites en commun',
  '452': 'Créances sur cessions d\'immobilisations',
  '453': 'Sécurité sociale et autres organismes sociaux',
  '454': 'Dettes sur acquisitions de valeurs mobilières de placement',
  '455': 'Créances sur cessions de valeurs mobilières de placement',
  '457': 'Autres comptes débiteurs ou créditeurs',
  '458': 'Diverses charges à payer et produits à recevoir',
  '461': 'Compte d\'attente',
  '465': 'Différence de conversion sur éléments courants',
  '468': 'Autres comptes transitoires',
  '471': 'Charges constatées d\'avance',
  '472': 'Produits constatés d\'avance',
  '478': 'Comptes de répartition périodique de charges et produits',
  '491': 'Provisions pour dépréciation des comptes clients',
  '494': 'Provisions pour dépréciation des comptes de groupe et associés',
  '495': 'Provisions pour dépréciation des comptes de débiteurs divers',
  '501': 'Emprunts courants liés au cycle d\'exploitation',
  '505': 'Échéances à moins d\'un an sur emprunts non courants',
  '506': 'Concours bancaires courants',
  '507': 'Emprunts échus et impayés',
  '508': 'Intérêts courus',
  '511': 'Prêts courants liés au cycle d\'exploitation',
  '516': 'Échéances à moins d\'un an sur prêts non courants',
  '517': 'Échéances à moins d\'un an sur autres créances financières',
  '518': 'Intérêts courus',
  '523': 'Actions',
  '524': 'Autres titres conférant un droit de propriété',
  '525': 'Obligations et bons émis par la société et rachetés par elle',
  '526': 'Obligations',
  '527': 'Bons du trésor et bons de caisse à court terme',
  '528': 'Autres placements courants et créances assimilées',
  '529': 'Versements restant à effectuer sur valeurs mobilières de placement non libérées',
  '531': 'Valeurs à l\'encaissement',
  '532': 'Banques',
  '534': 'C.C.P',
  '535': 'Comptes au trésor',
  '537': 'Autres organismes financiers',
  '541': 'Caisse siège social',
  '542': 'Caisses succursales',
  '601': 'Achats stockés - Matières premières et fournitures liées',
  '602': 'Achats stockés - Autres approvisionnements',
  '603': 'Variation des stocks (approvisionnements et marchandises)',
  '604': 'Achats d\'études et de prestations de services (y compris achat de sous-traitance de production)',
  '605': 'Achats de matériel, équipements et travaux',
  '606': 'Achats non stockés de matières et fournitures',
  '607': 'Achats de marchandises',
  '608': 'Achats liés à une modification comptable à prendre en compte dans le résultat de l\'exercice ou à une activité abandonnée',
  '609': 'Rabais, remises et ristournes obtenus sur achats',
  '611': 'Sous-traitance générale',
  '612': 'Redevances pour utilisation d\'immobilisations concédées',
  '613': 'Locations (y compris malis sur emballages)',
  '614': 'Charges locatives et de copropriété',
  '615': 'Entretien et réparations',
  '616': 'Primes d\'assurances',
  '617': 'Études, recherches et divers services extérieurs',
  '618': 'Autres charges liées à une modification comptable à prendre en compte dans le résultat de l\'exercice ou à une activité abandonnée',
  '619': 'Rabais, remises et ristournes obtenus sur services extérieurs',
  '621': 'Personnel extérieur à l\'entreprise',
  '622': 'Rémunération d\'intermédiaires et honoraires',
  '623': 'Publicité, publications, relations publiques',
  '624': 'Transports de biens et transports collectifs du personnel',
  '625': 'Déplacements, missions et réceptions',
  '626': 'Frais postaux et frais de télécommunications',
  '627': 'Services bancaires et assimilés',
  '628': 'Autres services extérieurs liés à une modification comptable à prendre en compte dans le résultat de l\'exercice ou à une activité abandonnée',
  '629': 'Rabais, remises et ristournes obtenus sur autres services extérieurs',
  '631': 'Redevances pour concessions de marques, brevets, licences, procédés, droits et valeurs similaires',
  '633': 'Jetons de présence',
  '634': 'Pertes sur créances irrécouvrables',
  '635': 'Quotes-parts de résultat sur opérations faites en commun',
  '636': 'Charges nettes sur cessions d\'immobilisations et autres pertes sur éléments non récurrents ou exceptionnels',
  '637': 'Réduction de valeur',
  '638': 'Charges diverses ordinaires liées à une modification comptable à prendre en compte dans le résultat de l\'exercice ou à une activité abandonnée',
  '640': 'Salaires et compléments de salaires',
  '642': 'Appointements et compléments d\'appointements',
  '643': 'Indemnités représentatives de frais',
  '644': 'Commissions au personnel',
  '645': 'Rémunérations des administrateurs, gérants et associés',
  '646': 'Charges connexes aux salaires, appointements, commissions et rémunérations',
  '647': 'Charges sociales légales',
  '648': 'Charges de personnel liées à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '649': 'Autres charges de personnel et autres charges sociales',
  '651': 'Charges d\'intérêts',
  '653': 'Pertes sur créances liées à des participations',
  '654': 'Escomptes accordés',
  '655': 'Pertes de change',
  '656': 'Charges nettes sur cessions de valeurs mobilières',
  '657': 'Autres charges financières',
  '658': 'Charges financières liées à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '661': 'Impôts, taxes et versements assimilés sur rémunérations',
  '665': 'Autres impôts, taxes et versements assimilés',
  '668': 'Impôts et taxes liés à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '681': 'Dotations aux amortissements et aux provisions - charges ordinaires (autres que financières)',
  '686': 'Dotations aux amortissements et aux provisions - charges financières',
  '691': 'Impôts sur les bénéfices calculés sur le résultat des activités ordinaires',
  '695': 'Autres impôts sur les bénéfices (régimes particuliers)',
  '697': 'Impôts sur les bénéfices calculés sur les éléments extraordinaires',
  '701': 'Ventes de produits finis',
  '702': 'Ventes de produits intermédiaires',
  '703': 'Ventes de produits résiduels',
  '704': 'Travaux',
  '705': 'Études et prestations de services',
  '706': 'Produits des activités annexes',
  '707': 'Ventes de marchandises',
  '708': 'Ventes liées à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '709': 'Rabais, remises et ristournes accordés par l\'entreprise',
  '713': 'Variation des stocks (en-cours de production, produits)',
  '721': 'Immobilisations incorporelles',
  '722': 'Immobilisations corporelles',
  '728': 'Production immobilisée liée à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '731': 'Redevances pour concessions, brevets, licences, marques, procédés, droits et valeurs similaires',
  '732': 'Revenus des immeubles non affectés aux activités professionnelles',
  '733': 'Jetons de présence et rémunérations d\'administrateurs, gérants',
  '734': 'Ristournes perçues des coopératives (provenant des excédents)',
  '735': 'Quotes-parts de résultat sur opérations faites en commun',
  '736': 'Produits nets sur cessions d\'immobilisations et autres gains sur éléments non récurrents ou exceptionnels',
  '738': 'Produits divers ordinaires liés à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '739': 'Quotes-parts des subventions d\'investissement inscrites au résultat de l\'exercice',
  '741': 'Subventions d\'exploitation',
  '745': 'Subventions d\'équilibre',
  '748': 'Subventions liées à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '751': 'Produits des participations',
  '752': 'Produits des autres immobilisations financières',
  '753': 'Revenus des autres créances',
  '754': 'Revenus des valeurs mobilières de placement',
  '755': 'Escomptes obtenus',
  '756': 'Gains de change',
  '757': 'Produits nets sur cessions de valeurs mobilières',
  '758': 'Produits financiers liés à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '781': 'Reprises sur amortissements et provisions (à inscrire dans les produits ordinaires)',
  '786': 'Reprises sur provisions (à inscrire dans les produits financiers)',
  '1011': 'Capital souscrit - non appelé',
  '1012': 'Capital souscrit - appelé, non versé',
  '1013': 'Capital souscrit - appelé, versé',
  '1018': 'Capital souscrit soumis à une réglementation particulière',
  '1171': 'Primes d\'émission',
  '1172': 'Primes de fusion',
  '1173': 'Primes d\'apport',
  '1174': 'Primes de conversion d\'obligation',
  '1178': 'Autres compléments d\'apport',
  '1181': 'Réserves pour fonds social',
  '1421': 'Réserves indisponibles',
  '1451': 'Subventions d\'investissement',
  '1458': 'Autres subventions d\'investissement',
  '1459': 'Subventions d\'investissement inscrites aux comptes de résultat',
  '1511': 'Provisions pour litiges',
  '1512': 'Provisions pour garanties données aux clients',
  '1513': 'Provisions pour pertes sur marchés à achèvement futur',
  '1514': 'Provisions pour amendes & pénalités',
  '1515': 'Provisions pour pertes de change',
  '1518': 'Autres provisions pour risques',
  '1522': 'Provisions pour grosses réparations',
  '1611': 'Emprunts obligataires convertibles en actions',
  '1618': 'Autres emprunts obligataires',
  '1621': 'Emprunts bancaires',
  '1626': 'Refinancements acquis',
  '1641': 'Avances bloquées pour augmentation du capital',
  '1642': 'Avances reçues et comptes courants des associés bloqués',
  '1644': 'Avances conditionnées de l\'Etat & organismes internationaux',
  '1661': 'Dettes rattachées à des participations (groupe)',
  '1662': 'Dettes rattachées à des participations (hors groupe)',
  '1663': 'Dettes rattachées à des sociétés en participation',
  '1681': 'Autres emprunts',
  '1685': 'Crédit fournisseurs d\'immobilisations',
  '1688': 'Autres dettes non courantes',
  '2213': 'Terrains nus',
  '2214': 'Terrains aménagés',
  '2215': 'Terrains bâtis',
  '2216': 'Agencements & aménagements des terrains',
  '2221': 'Bâtiments',
  '2225': 'Installations générales, agencements & aménagements des constructions',
  '2226': 'Ouvrages d\'infrastructure',
  '2227': 'Constructions sur sol d\'autrui',
  '2231': 'Installations techniques',
  '2234': 'Matériel industriel',
  '2235': 'Outillage industriel',
  '2237': 'Agencements & aménagements du matériel & outillage industriels',
  '2241': 'Matériel de transport de biens',
  '2244': 'Matériel de transport de personnes',
  '2281': 'Installations générales, agencements et aménagements divers',
  '2282': 'Équipement de bureau',
  '2286': 'Emballages récupérables identifiables',
  '2511': 'Actions',
  '2518': 'Autres titres',
  '2571': 'Créances rattachées à des participations (groupe)',
  '2574': 'Créances rattachées à des participations (hors groupe)',
  '2575': 'Versements représentatifs d\'apports non capitalisés (appel de fonds)',
  '2576': 'Avances consolidables',
  '2577': 'Autres créances rattachées à des participations',
  '2611': 'Actions',
  '2618': 'Autres titres',
  '2621': 'Obligations',
  '2622': 'Bons',
  '2641': 'Prêts participatifs',
  '2642': 'Prêts aux associés',
  '2643': 'Prêts au personnel',
  '2645': 'Prêts assortis de sûretés',
  '2648': 'Autres prêts',
  '2651': 'Dépôts',
  '2655': 'Cautionnements',
  '2656': 'Dépôts bancaires non courants',
  '2658': 'Autres',
  '2661': 'Créances immobilisées',
  '2667': 'Créances diverses',
  '2668': 'Autres créances non courantes',
  '4011': 'Fournisseurs - achats de biens ou de prestations de services',
  '4017': 'Fournisseurs - retenues de garantie',
  '4041': 'Fournisseurs - achats d\'immobilisations',
  '4047': 'Fournisseurs d\'immobilisations - retenues de garantie',
  '4081': 'Fournisseurs d\'exploitation',
  '4084': 'Fournisseurs d\'immobilisations',
  '4088': 'Fournisseurs - intérêts courus',
  '4091': 'Fournisseurs - avances et acomptes versés sur commandes',
  '4096': 'Fournisseurs - créances pour emballages et matériel à rendre',
  '4097': 'Fournisseurs - autres avoirs',
  '4098': 'Rabais, remises, ristournes à obtenir et autres avoirs non encore reçus',
  '4111': 'Clients - ventes de biens ou de prestations de services',
  '4117': 'Clients - retenues de garantie',
  '4181': 'Factures à établir',
  '4188': 'Intérêts courus',
  '4191': 'Clients - avances et acomptes reçus sur commandes',
  '4196': 'Clients - dettes pour emballages et matériel consignés',
  '4197': 'Clients - autres avoirs',
  '4198': 'Rabais, remises, ristournes à accorder et autres avoirs à établir',
  '4282': 'Dettes provisionnées pour congés à payer',
  '4286': 'Autres charges à payer',
  '4287': 'Produits à recevoir',
  '4341': 'Retenue à la source',
  '4342': 'Acomptes provisionnels',
  '4343': 'Impôt à liquider',
  '4349': 'Impôts différés',
  '4365': 'Taxes sur le chiffre d\'affaires à décaisser',
  '4366': 'Taxes sur le chiffre d\'affaires déductibles',
  '4367': 'Taxes sur le chiffre d\'affaires collectées par l\'entreprise',
  '4368': 'Taxes sur le chiffre d\'affaires à régulariser ou en attente',
  '4382': 'Charges fiscales sur congés à payer',
  '4386': 'Autres charges à payer',
  '4387': 'Produits à recevoir',
  '4411': 'Créances et intérêts courus',
  '4412': 'Dettes et intérêts à payer',
  '4421': 'Principal',
  '4428': 'Intérêts courus',
  '4481': 'Opérations courantes',
  '4488': 'Intérêts courus',
  '4531': 'Organismes sociaux',
  '4538': 'Organismes sociaux - charges à payer et produits à recevoir',
  '4586': 'Charges à payer',
  '4587': 'Produits à recevoir',
  '4651': 'Différences de conversion actif',
  '4652': 'Différences de conversion passif',
  '4786': 'Charges',
  '4787': 'Produits',
  '4941': 'Comptes du groupe',
  '4942': 'Comptes courants des associés',
  '4948': 'Opérations faites en commun',
  '4952': 'Créances sur cession d\'immobilisation',
  '4955': 'Créances sur cession des valeurs mobilières de placement',
  '4957': 'Autres comptes débiteurs',
  '5061': 'Crédit de mobilisation de créances commerciales',
  '5063': 'Mobilisation de créances nées à l\'étranger',
  '5067': 'Autres concours bancaires',
  '5231': 'Titres cotés',
  '5235': 'Titres non cotés',
  '5261': 'Titres cotés',
  '5265': 'Titres non cotés',
  '5266': 'Échéances à moins d\'un an sur les obligations immobilisées',
  '5281': 'Autres valeurs mobilières',
  '5288': 'Intérêts courus sur obligations, bons et valeurs assimilées',
  '5311': 'Coupons échus à l\'encaissement',
  '5312': 'Chèques à encaisser',
  '5313': 'Effets à l\'encaissement',
  '5314': 'Effets à l\'escompte',
  '5321': 'Comptes en dinars',
  '5324': 'Comptes en devises',
  '5411': 'Caisse en dinars',
  '5414': 'Caisse en devises',
  '6021': 'Matières consommables',
  '6022': 'Fournitures consommables',
  '6026': 'Emballages',
  '6098': 'Liés à une modification comptable à prendre en compte dans le résultat de l\'exercice ou à une activité abandonnée',
  '6241': 'Transports sur achats',
  '6242': 'Transports sur ventes',
  '6244': 'Transports administratifs',
  '6247': 'Transports collectifs du personnel',
  '6248': 'Divers',
  '6251': 'Voyages et déplacements',
  '6255': 'Frais de déménagement',
  '6256': 'Missions',
  '6257': 'Réceptions',
  '6271': 'Frais sur titres (achats, vente, garde)',
  '6272': 'Commissions et frais sur émission d\'emprunts',
  '6275': 'Frais sur effets',
  '6276': 'Location de coffres',
  '6278': 'Autres frais et commissions sur prestations de services',
  '6341': 'Créances de l\'exercice',
  '6344': 'Créances des exercices antérieurs',
  '6351': 'Quote-part de bénéfice transférée (comptabilité du gérant)',
  '6355': 'Quote-part de perte supportée (comptabilité des associés non gérants)',
  '6400': 'Salaires',
  '6401': 'Heures supplémentaires',
  '6402': 'Primes',
  '6403': 'Gratifications',
  '6404': 'Avantages en nature',
  '6409': 'Autres compléments de salaires',
  '6420': 'Appointements',
  '6421': 'Heures supplémentaires',
  '6422': 'Primes',
  '6423': 'Gratifications',
  '6424': 'Avantages en nature',
  '6429': 'Autres compléments d\'appointements',
  '6440': 'Commissions sur achats',
  '6441': 'Commissions sur ventes',
  '6460': 'Charges connexes aux salaires',
  '6462': 'Charges connexes aux appointements',
  '6464': 'Charges connexes aux commissions',
  '6465': 'Charges connexes aux rémunérations des administrateurs et gérants',
  '6470': 'Cotisations de sécurité sociale sur salaires',
  '6472': 'Cotisations de sécurité sociale sur appointements',
  '6474': 'Cotisations de sécurité sociale sur commissions',
  '6475': 'Cotisations de sécurité sociale sur rémunérations des administrateurs et gérants',
  '6476': 'Prestations directes',
  '6490': 'Autres charges de personnel',
  '6495': 'Autres charges sociales',
  '6511': 'Intérêts des emprunts et dettes',
  '6515': 'Intérêts des comptes courants et des dépôts créditeurs',
  '6516': 'Intérêts bancaires et sur opérations de financement',
  '6517': 'Intérêts des obligations cautionnées',
  '6518': 'Intérêts des autres dettes (y compris les pénalités et intérêts de retard sur emprunts)',
  '6611': 'TFP',
  '6612': 'FOPROLOS',
  '6618': 'Autres',
  '6651': 'Impôts et taxes divers (sauf impôts sur les bénéfices)',
  '6652': 'Taxes sur le chiffre d\'affaires non récupérables',
  '6654': 'Droits d\'enregistrement et de timbre',
  '6655': 'Taxes sur les véhicules',
  '6658': 'Autres droits',
  '6811': 'Dotations aux amortissements des immobilisations incorporelles et corporelles',
  '6812': 'Dotations aux résorptions des charges reportées',
  '6815': 'Dotations aux provisions pour risques et charges d\'exploitation',
  '6816': 'Dotations aux provisions pour dépréciation des immobilisations incorporelles et corporelles',
  '6817': 'Dotations aux provisions pour dépréciation des actifs courants (autres que les valeurs mobilières de placement et les équivalents de liquidités)',
  '6818': 'Dotations aux amortissements et aux provisions liées à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '6861': 'Dotations aux amortissements des primes de remboursement des obligations',
  '6865': 'Dotations aux provisions pour risques et charges financières',
  '6866': 'Dotations aux provisions pour dépréciation des éléments financiers',
  '6868': 'Dotations aux amortissements et aux provisions liées à une modification comptable inscrite dans le résultat de l\'exercice ou à une activité abandonnée. (charges financières)',
  '7011': 'Produits finis achevés',
  '7012': 'Produits finis non achevés (contrat de longue durée)',
  '7091': 'Sur ventes de produits finis',
  '7092': 'Sur ventes de produits intermédiaires',
  '7094': 'Sur travaux',
  '7095': 'Sur études et prestations de services',
  '7096': 'Sur activités annexes',
  '7097': 'Sur ventes de marchandises',
  '7098': 'Sur ventes liées à une modification comptable à imputer au résultat de l\'exercice ou à une activité abandonnée',
  '7133': 'Variations des en-cours de production de biens',
  '7134': 'Variation des en-cours de production de services',
  '7135': 'Variation des stocks de produits',
  '7811': 'Reprises sur amortissements des immobilisations incorporelles et corporelles',
  '7815': 'Reprises sur provisions pour risques et charges d\'exploitation',
  '7816': 'Reprises sur provisions pour dépréciation des immobilisations incorporelles et corporelles',
  '7817': 'Reprises sur provisions pour dépréciation des actifs courants (autres que les valeurs mobilières de placement et les équivalents de liquidités)',
  '7818': 'Reprises sur provisions liées à une modification comptable inscrite aux résultats ou à une activité abandonnée',
  '10131': 'Capital non amorti',
  '10132': 'Capital amorti',
  '40971': 'Fournisseurs d\'exploitation',
  '40974': 'Fournisseurs d\'immobilisations',
  '43651': 'TVA à payer',
  '43658': 'Autres taxes sur le chiffre d\'affaires',
  '43662': 'TVA sur immobilisations',
  '43663': 'TVA transférée par d\'autres entreprises',
  '43666': 'TVA sur autres biens et services',
  '43667': 'Crédit de TVA à reporter',
  '43668': 'Autres taxes sur le chiffre d\'affaires',
  '43671': 'TVA collectée',
  '43674': 'Retenue à la source',
  '43678': 'Autres taxes sur le chiffre d\'affaires',
  '44550': 'TVA déductible',
  '45311': 'CNSS',
  '45318': 'Autres',
  '45382': 'Charges sociales sur congés à payer',
  '45386': 'Autres charges à payer',
  '45387': 'Produits à recevoir',
  '64600': 'Congés payés',
  '64602': 'Indemnités de préavis et de licenciements (gratification de fin de service)',
  '64604': 'Supplément familial',
  '64620': 'Congés payés',
  '64622': 'Indemnités de préavis et de licenciement (gratification de fin de service)',
  '64624': 'Supplément familial',
  '64640': 'Congés payés',
  '64642': 'Indemnités de préavis et de licenciement (gratification de fin de service)',
  '64644': 'Supplément familial',
  '64650': 'Congés payés',
  '64652': 'Indemnités de préavis et de licenciement',
  '64654': 'Supplément familial',
  '65116': 'Des emprunts et dettes assimilées',
  '65117': 'Des dettes rattachées à des participations',
  '68111': 'Immobilisations incorporelles',
  '68112': 'Immobilisations corporelles',
  '68161': 'Immobilisations incorporelles',
  '68162': 'Immobilisations corporelles',
  '68173': 'Stocks et en-cours',
  '68174': 'Créances',
  '68662': 'Immobilisations financières',
  '68665': 'Placements et prêts courants',
  '78111': 'Immobilisations incorporelles',
  '78112': 'Immobilisations corporelles',
  '78161': 'Immobilisations incorporelles',
  '78162': 'Immobilisations corporelles',
  '78173': 'Stocks et en-cours',
  '78174': 'Créances',
  '101000': 'Capital social',
  '105000': 'Fonds de dotation',
  '401000': 'Fournisseur',
  '411000': 'Client',
  '436711': 'TVA collectée sur les débits',
  '436712': 'TVA collectée sur les encaissements',
  '445000': 'TVA',
  '512000': 'Banque',
  '530000': 'Caisse',
  '601000': 'Achat marchandises',
  '602000': 'Autres approvisionnements',
  '604000': 'Prestation de services reçue',
  '606000': 'Achat non stocké',
  '607000': 'Achat marchandises revendues',
  '611000': 'Sous-traitance',
  '613000': 'Loyer',
  '614000': 'Charges locatives',
  '616000': 'Prime d\'assurance',
  '622200': 'Honoraires',
  '623000': 'Publicité et communication',
  '624000': 'Frais de transport',
  '626000': 'Frais télécom et postaux',
  '627000': 'Frais bancaires',
  '640000': 'Charges de personnel',
  '645000': 'Cotisations CNSS',
  '681000': 'Dotation aux amortissements',
  '700000': 'Vente de marchandises',
  '706000': 'Prestations de services',
  '708000': 'Autres produits',
  '10100000': 'Capital social',
  '10500000': 'Fonds de dotation',
  '40100000': 'Fournisseur',
  '41100000': 'Client',
  '44500000': 'TVA',
  '51200000': 'Banque',
  '53000000': 'Caisse',
  '60100000': 'Achat marchandises',
  '60200000': 'Autres approvisionnements',
  '60400000': 'Prestation de services reçue',
  '60600000': 'Achat non stocké',
  '60700000': 'Achat marchandises revendues',
  '61100000': 'Sous-traitance',
  '61300000': 'Loyer',
  '61400000': 'Charges locatives',
  '61600000': 'Prime d\'assurance',
  '62220000': 'Honoraires',
  '62300000': 'Publicité et communication',
  '62400000': 'Frais de transport',
  '62600000': 'Frais télécom et postaux',
  '62700000': 'Frais bancaires',
  '64000000': 'Charges de personnel',
  '64500000': 'Cotisations CNSS',
  '68100000': 'Dotation aux amortissements',
  '70000000': 'Vente de marchandises',
  '70600000': 'Prestations de services',
  '70800000': 'Autres produits',
  '80': 'Engagements donnés',
  '81': 'Engagements reçus',
  '83': 'Stocks hors exploitation',
  '84': 'Comptes de fusion',
  '85': 'Comptes de consolidation',
  '86': 'Comptes spéciaux divers',
  '87': 'Comptes de gestion spéciale',
  '88': 'Résultats spéciaux',
  '89': 'Comptes de bilan spéciaux',
};
