// ==========================================================================
//  supabaseService → cloudClient (Cloudflare Workers + D1)
//  Garde le même nom d'exports pour ne pas casser les appelants.
// ==========================================================================
export {
  isSupabaseEnabled,
  signUp,
  signIn,
  signOut,
  getSession,
  getCurrentUser,
  onAuthChange,
  hasSession,
  getProfile,
  updateProfile,
  getUserCompanies,
  createCompany,
  updateCompany,
  fetchCompanySettings,
  saveCompanySettings,
  fetchData,
  fetchDataSince,
  upsertData,
  insertData,
  updateData,
  updateDataById,
  deleteData,
  deleteDataById,
  importToCloud,
  migrateLocalToSupabase,
  initNetworkListener,
  flushOfflineQueue,
  setApiToken,
  getApiToken,
} from './cloudClient';
